
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: talosoft
    url: jdbc:mysql://localhost:3306/xxx?characterEncoding=utf8&useSSL=false&allowMultiQueries=true

